name: tt_bindings
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
